### PR TITLE
Uploadable extension

### PR DESCRIPTION
**Pull request by jee7**
Uploadable extension implementation.
Uploadable extension needs to register the uploadableListener in order to access it from the app (see use: https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/uploadable.md ).
I also added a facade for easier access. Users can register the facade if they prefer that.

### CODE REVIEW

**Comment by mbbender** [comment]
The problem I have with this implementation is that the register function ends up being pulled out of the proper register workflow of laravel since by moving the `register` function into the Extension manager like this you end up only registering it once the first instance of the Extension manager is resolved (which is after all provides/registering should be done). 

It seems to me since the uploadable extension is more in depth than others and appears to require another class bound into the IoC, it should just be it's own simple service provider and leverage laravel without any need to do something specific in the laravel-doctrine integration. 

With a new service provider (which would remove the register stuff from the extensions/orm) you should be able to use your class as is with what is there now right (the addSubscribers and Filters should still work as expected)? 

In full disclosure I think the entire extension manager concept, while good, can be refactored into a few configs and their own specific classes as needed. Doctrine doesn't have a singular concept of 'extension' so I'd like to see us move more to SRP as well as follow doctrine terminology/concepts more closely as we move to version 1.

**Comment by jee7** [comment]
Ok, what about now?

I removed the register from the ExtensionManager. Added a UploadableServiceProvider that now registers the uploadableListener singleton. Users need to add that service provider to their application conf. In addition to enabling it in the doctrine conf.

app.php

```
'providers' => [
        ...
        LaravelDoctrine\ORM\DoctrineServiceProvider::class,
        LaravelDoctrine\Extensions\Uploadable\UploadableServiceProvider::class,
]
```

doctrine.php

```
'extensions' => [
        ...
        LaravelDoctrine\Extensions\Uploadable\UploadableExtension::class,
],
```

**Comment by mbbender** [comment]
I think that is closer to what I was thinking as a way to keep you moving forward without us having to accept any pull requests immediately. I believe @patrickbrouwers was hoping to put some thought on this extension so we'll defer on merging until he has a chance after his work sprint to look into this. But for now you are unblocked and feel ok to use this in your project without having to execute this PR right?

**Comment by patrickbrouwers** [comment]
I do like the ServiceProvider approach a lot better, however here are some remarks:
- Extension classes are resolved from the ioContainer, so you can use dependency injection. 

``` php
class UploadableExtension implements Extension
{
    public function __construct(UploadableListener $listener)
    {
        // etc.
    }
}
```

Now you can use this injected listener to set on the event manager, this will remove the not-easily testable `App::bound` and `app()` helpers (which also just doesn't really look clean IMHO).
- Can you please use `$this->app` in favour of the facade. And you can now bind it to `$this->app->singleton(UploadableListener::class)`
  (Could you also add in the default register docblock (from ServiceProvider))
- Update the facade to `return UploadableListener::class` as well then.
- General point: can you remove the PhpStorm comments on top and make sure all files are PSR-2 (you can simply run `php-cs-fixer fix`, because a config file is provided /// https://github.com/FriendsOfPHP/PHP-CS-Fixer)

When finished, can you squash all commits into one, please?

**Comment by jee7** [comment]
Alright. Better now? 
When uploading, one can use either:

```
app(UploadableListener::class)->addEntityFileInfo($entity, $fileInfo);
```

or

```
\Uploadable::addEntityFileInfo($entity, $fileInfo);
```

**Comment by patrickbrouwers** [comment]
Wondering now if this works on multiple connections.

**Pull request merged**
