### PR TITLE
Add attribute support for softdeletable

### PR DESCRIPTION
**Pull request by mleczakm**

### CODE REVIEW

**Comment by krowinski** [comment]
Hi @eigan, can you merge this or this need further discussion ?

**Comment by eigan** [comment]
Yeah, sorry!

**Comment by eigan** [comment]
Released with 1.5.3. Thank you @mleczakm !

**Comment by krowinski** [comment]
Tx!

**Comment by dpslwk** [comment]
We should also add attributes to
`IpTraceable`
`Timestamps`
`NestedSet`

**Pull request merged**
